function trackers=configTrackers

% trackersVIVID={
%     struct('name','VR','namePaper','VR-V'),...%gray-25%
%     struct('name','TM','namePaper','TM-V'),...%dark red
%    struct('name','RS','namePaper','RS-V'),...%orange
%    struct('name','PD','namePaper','PD-V'),...%Turquoise
%    struct('name','MS','namePaper','MS-V')%purple
% };
%    struct('name','TLD','namePaper','TLD'),...%%有error
%    struct('name','LSK','namePaper','LSK'),...%%有error
%    struct('name','ASLA','namePaper','ASLA'),...%%有error

trackers1={  struct('name','CT','namePaper','CT'),...
    struct('name','MTT','namePaper','MTT'),...
    struct('name','CSK','namePaper','CSK'),...  
    struct('name','SCT','namePaper','SCT'),...
    struct('name','IVT','namePaper','IVT'),...
    struct('name','DFT','namePaper','DFT'),...%yellow
    struct('name','L1APG','namePaper','L1APG'),...    
    struct('name','ORIA','namePaper','ORIA'),...
    struct('name','Struck','namePaper','Struck'),...
    struct('name','LOT','namePaper','LOT')  
    };
 

trackersEXE={ struct('name','CPF','namePaper','CPF'),...
    struct('name','Struck','namePaper','Struck'),...
    struct('name','MIL','namePaper','MIL'),... 
    struct('name','SBT','namePaper','SemiT'),...
    struct('name','BSBT','namePaper','BSBT'),...
    struct('name','Frag','namePaper','Frag'),...
    struct('name','KMS','namePaper','KMS'),...
    struct('name','SMS','namePaper','SMS'),...
    struct('name','VTS','namePaper','VTS'),...
    struct('name','VTD','namePaper','VTD'),...
    struct('name','CXT','namePaper','CXT')
    };
 trackersNEW={    struct('name','MTT','namePaper','MTT'),...
     struct('name','CT','namePaper','CT'),...
     struct('name','CSK','namePaper','CSK'),...
    struct('name','IVT','namePaper','IVT'),...
     struct('name','ORIA','namePaper','ORIA'),...
      struct('name','SPC','namePaper','SPC'),...
    struct('name','OCT','namePaper','OCT'),...
     struct('name','MTT','namePaper','MTT'),...
     struct('name','DFT','namePaper','DFT')};

%  trackersNEW={ struct('name','KCF_DCT','namePaper','KCF_DCT')};
  trackersNEW={ struct('name','OAB','namePaper','OAB'),...
       struct('name','OCT','namePaper','OCT'),...
      struct('name','fDSST','namePaper','fDSST'),...
      struct('name','CT','namePaper','CT'),...
      struct('name','CSK','namePaper','CSK'),...
      struct('name','IVT','namePaper','IVT'),...
      struct('name','ORIA','namePaper','ORIA'),...
      struct('name','KCF','namePaper','KCF'),...
      struct('name','KCF_AST','namePaper','KCF_AST'),...
      struct('name','DFT','namePaper','DFT')....
      struct('name','SPC','namePaper','SPC'),...
      struct('name','MTT','namePaper','MTT'),...
      struct('name','L1APG','namePaper','L1APG'),...
      struct('name','LOT','namePaper','LOT'),...
      struct('name','Frag','namePaper','Frag'),...
      struct('name','SBT','namePaper','SemiT'),...
      struct('name','BSBT','namePaper','BSBT'),...
       struct('name','LCCF','namePaper','LCCF'),....
        struct('name','LCCF_AST','namePaper','LCCF_AST').... 
      struct('name','KMS','namePaper','KMS'),...
      struct('name','SMS','namePaper','SMS'),...
      struct('name','CPF','namePaper','CPF'),...
      struct('name','MDNet','namePaper','MDNet'),....
      struct('name','MDNet_AST','namePaper','MDNet_AST'),....
       struct('name','SCM','namePaper','SCM'),... 
       struct('name','SCT4','namePaper','SCT4'),...
  };

% struct('name','KCF_DCT','namePaper','KCF_DCT'),... 
%  struct('name','KCF_QDCT','namePaper','KCF_QDCT'),...

% % % %       trackersNEW={   struct('name','KCF','namePaper','KCF'),...
% % % %        struct('name','CSK','namePaper','CSK'),...
% % % %       };
%   struct('name','KCF_IS','namePaper','KCF_IS'),... 
%  struct('name','KCF_QIS','namePaper','KCF_QIS'),...
%       struct('name','KCF_AST','namePaper','KCF_AST'),...
%        struct('name','SCT4','namePaper','SCT4'),...
%             struct('name','SPC','namePaper','SPC'),...    
%
%%
%YJY
%   trackersYJY={struct('name','KCF','namePaper','KCF'),...
%       struct('name','KCF_AS','namePaper','KCF_AS'),...
%        struct('name','LCCF','namePaper','LCCF'),...
%         struct('name','LCCF_AS','namePaper','LCCF_AS'),...
%          struct('name','MDNet','namePaper','MDNet'),...
%         struct('name','MDNet_AS','namePaper','MDNet_AS'),...
%          struct('name','SPC','namePaper','SPC'),...
%         struct('name','OAB','namePaper','OAB'),...
%         struct('name','MTT','namePaper','MTT'),...
%         struct('name','CSK','namePaper','CSK'),...   
%         struct('name','CT','namePaper','CT'),...
%     struct('name','DFT','namePaper','DFT')....         
%       struct('name','IVT','namePaper','IVT'),...            
% };

%      trackersNEW={ struct('name','OCT','namePaper','OCT'),...
%    };

%   trackersNEW={ struct('name','KCF','namePaper','KCF'),...
%       struct('name','KCF_AST','namePaper','KCF_AST'),...
%       };
% %      
%         struct('name','KCF_IS','namePaper','KCF_IS'),...
%           struct('name','KCF_QIS','namePaper','KCF_QIS'),...
% %     
%      
%       

trackers={ struct('name','KCF_AS','namePaper','KCF_AS'),...
struct('name','KCF','namePaper','KCF'),... struct('name','OAB','namePaper','OAB'),...
       struct('name','OCT','namePaper','OCT'),...
    
  };
 trackers={  struct('name','OCT','namePaper','OCT'),...
      struct('name','KCF','namePaper','KCF'),...
      struct('name','KCF_AS','namePaper','KCF_AST'),...
      struct('name','DFT','namePaper','DFT')....
      struct('name','SPC','namePaper','SPC'),...
 struct('name','LOT','namePaper','LOT'),...
      struct('name','MTT','namePaper','MTT'),...
      struct('name','L1APG','namePaper','L1APG'),...
        };
    
     trackers_small90={ struct('name','OAB','namePaper','OAB'),...
      struct('name','OCT','namePaper','OCT'),...
      struct('name','fDSST','namePaper','fDSST'),...
      struct('name','CT','namePaper','CT'),...
      struct('name','CSK','namePaper','CSK'),...
      struct('name','IVT','namePaper','IVT'),...
      struct('name','ORIA','namePaper','ORIA'),...
      struct('name','KCF','namePaper','KCF'),...
      struct('name','KCF_AST','namePaper','KCF_AST'),...
      struct('name','DFT','namePaper','DFT')....
      struct('name','SPC','namePaper','SPC'),...
      struct('name','MTT','namePaper','MTT'),...
      struct('name','L1APG','namePaper','L1APG'),...
      struct('name','LOT','namePaper','LOT'),...
      struct('name','Frag','namePaper','Frag'),...
      struct('name','SBT','namePaper','SemiT'),...
      struct('name','BSBT','namePaper','BSBT'),...
      struct('name','LCCF','namePaper','LCCF'),....
      struct('name','LCCF_AST','namePaper','LCCF_AST').... 
      struct('name','KMS','namePaper','KMS'),...
      struct('name','SMS','namePaper','SMS'),...
      struct('name','CPF','namePaper','CPF'),...
      struct('name','SCT4','namePaper','SCT4'),...
      struct('name','MDNet_AST','namePaper','MDNet_AST'),....
      struct('name','MDNet','namePaper','MDNet'),....      
      struct('name','ECO_HC','namePaper','ECO'),...
      struct('name','ECO_HC_AST','namePaper','ECO_AST'),...
      struct('name','LCT','namePaper','LCT'),...
      struct('name','TLD','namePaper','TLD'),...
      struct('name','LDES','namePaper','LDES'),...
      struct('name','LDES_AST','namePaper','LDES_AST'),...
      struct('name','SAT','namePaper','SAT'),...
        struct('name','SiamRPN_ori','namePaper','DaSiamRPN'),...
       struct('name','SiamRPN_ori - 副本','namePaper','DaSiamRPN_AST'),...
      struct('name','SAT1','namePaper','SAT_AST'),...
      struct('name','SAT_AST','namePaper','SAT'),...
  };    
%  struct('name','SiamRPN1','namePaper','SiamRPN1'),...
 % struct('name','YJY','namePaper','SCT'),...

%    trackers= {        struct('name','KCF','namePaper','KCF'),...
%    struct('name','MDNet','namePaper','MDNet'),....  
%        struct('name','ECO_HC','namePaper','ECO'),...
%     struct('name','LCCF','namePaper','LCCF'),....
%  };
%trackersVIVID,

 trackers_uav20l={             struct('name','SiamRPN','namePaper','DaSiamRPN'),...
     struct('name','SiamRPN1','namePaper','DaSiamRPN_AST'),...
            struct('name','SRDCF_AST','namePaper','SRDCF_AST'),...
       struct('name','LCCF_AST','namePaper','LCCF_AST'),...
       struct('name','SRDCF','namePaper','SRDCF'),...
       struct('name','KCF_AST','namePaper','KCF_AST'),...
       struct('name','MEEM','namePaper','MEEM'),...
       struct('name','DSST','namePaper','DSST'),...
       struct('name','SAMF','namePaper','SAMF'),...
       struct('name','Struck','namePaper','Struck'),...
       struct('name','LCCF','namePaper','LCCF'),...
       struct('name','ASLA','namePaper','ASLA'),...
       struct('name','TLD','namePaper','TLD'),...
        struct('name','LCT','namePaper','LCT'),...
       struct('name','IVT','namePaper','IVT'),...
       struct('name','CSK','namePaper','CSK'),...
       struct('name','SAT1','namePaper','SAT'),...
       struct('name','LDESAST','namePaper','LDES_AST'),...
       struct('name','LDES','namePaper','LDES'),...
       struct('name','OCT','namePaper','OCT'),...
        struct('name','KCF_LinearHog','namePaper','KCF'),...
}

trackers_10fps={  struct('name','SRDCF_AST','namePaper','SRDCF_AST'),...
    struct('name','ECO_HC_AST','namePaper','ECO_HC_AST'),...
    struct('name','KCF_AS','namePaper','KCF_AST'),...
    struct('name','SiamRPN1AST1','namePaper','DaSiamRPN_AST'),...
    struct('name','LDES','namePaper','LDES'),...
    struct('name','SiamRPN1','namePaper','DaSiamRPN'),...
    struct('name','LDESAST1','namePaper','LDES_AST'),...
    struct('name','SAT1AST1','namePaper','SAT_AST'),...
    struct('name','ECO_HC','namePaper','ECO_HC'),...
    struct('name','MDNet_SCT','namePaper','MDNet_AST'),...
    struct('name','KCF_GaussHog','namePaper','KCF'),...
    struct('name','MDNet','namePaper','MDNet'),...
    struct('name','SRDCF','namePaper','SRDCF'),...
    struct('name','SAT1','namePaper','SAT'),...
    struct('name','DSST','namePaper','DSST'),...
    struct('name','TLD','namePaper','TLD'),...
    struct('name','MUSTER','namePaper','MUSTER'),...
    struct('name','SAMF','namePaper','SAMF'),...
    struct('name','Struck','namePaper','Struck'),...
    struct('name','OCT','namePaper','OCT'),...
    struct('name','LCT','namePaper','LCT'),...
    }; %    %struct('name','LCT','namePaper','LCT'),...    struct('name','KCF_AST','namePaper','KCF_AST'),...
% struct('name','SAT','namePaper','SAT'),...
%    struct('name','OCT','namePaper','OCT'),...
 trackers =   trackers_uav20l;
 %      struct('name','SAT_AST','namePaper','SAT_AST'),...

   trackers_small112={          struct('name','ECO_HC_AST','namePaper','ECO_AST'),...
       struct('name','LCCF_AST','namePaper','LCCF_AST'),...
       struct('name','ECO_HC','namePaper','ECO'),...
       struct('name','KCF_AST','namePaper','KCF_AST'),...
       struct('name','KCF','namePaper','KCF'),...
       struct('name','LCCF','namePaper','LCCF'),...
        struct('name','SCT','namePaper','SCT'),...
         struct('name','IVT','namePaper','IVT'),...
         struct('name','CSK','namePaper','CSK'),...
               struct('name','SAT1','namePaper','SAT_AST'),...
      struct('name','SAT_AST','namePaper','SAT'),...
            struct('name','LCT','namePaper','LCT'),...
      struct('name','TLD','namePaper','TLD'),...
            struct('name','LDES','namePaper','LDES'),...
      struct('name','LDES_AST','namePaper','LDES_AST'),...
      struct('name','OCT','namePaper','OCT'),...
      struct('name','SiamRPN_ori','namePaper','DaSiamRPN'),...
       struct('name','SiamRPN_ori - 副本','namePaper','DaSiamRPN_AST'),...
       }
%         
 trackers =   trackers_10fps;   

trackers = trackers_uav20l
 % trackers =   trackers_uav20l;
 %   trackers =  trackers_small90;
  %      trackers =  trackers_small112;
%        struct('name','MEEM','namePaper','MEEM'),...
%        struct('name','DSST','namePaper','DSST'),...
%        struct('name','SAMF','namePaper','SAMF'),...
%        struct('name','Struck','namePaper','Struck'),...
%        struct('name','LCCF','namePaper','LCCF'),...
%        struct('name','ASLA','namePaper','ASLA'),...
%        struct('name','TLD','namePaper','TLD'),...
%        struct('name','IVT','namePaper','IVT'),...
%        struct('name','CSK','namePaper','CSK'),...
%       } 

        % struct('name','MOSSE','namePaper','MOSSE'),...
         %           struct('name','DCF','nameP0000000000000000000000000000000000000000000000000000000000aper','DCT'),...

trackers = {
    struct('name','LDES','namePaper','LDES'),...
    struct('name','SiamRPN','namePaper','DaSiamRPN'),...
    struct('name','LDES_AST','namePaper','LDES_AST'),...
    struct('name','SiamRPN_AST','namePaper','DaSiamRPN_AST'),...
}
